version: 2.1
orbs:
  snyk: snyk/snyk@1.1.0
workflows:
  version: 2
  build:
    jobs:
      - build_test
jobs:
  build_test:
    working_directory: ~/
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - snyk/scan